version: 0.0
os: linux
files:
  - source: source_code/Hi/build/libs/hi-1.0-SNAPSHOT.jar
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: deployment_scripts/CleanupOldVersion.sh
      runas: root
  ApplicationStart:
    - location: deployment_scripts/AppStart.sh
      runas: root
  ApplicationStop:
    - location: deployment_scripts/AppStop.sh
      runas: root