version: 0.1
phases:
  build:
    commands:
      - sed -i -e "s#username_here#${DB_USERNAME}#" source_code/Hi/src/main/resources/application.properties
      - sed -i -e "s#password_here#${DB_PASSWORD}#" source_code/Hi/src/main/resources/application.properties
      - sed -i -e "s#dbUrl_here#jdbc:mysql://${DB_LINK}:3306/${DB_Name}#" source_code/Hi/src/main/resources/application.properties
      - gradle build -p source_code/Hi/
artifacts:
  type: zip
  files:
    - appspec.yml
    - deployment_scripts/AppStart.sh
    - deployment_scripts/AppStop.sh
    - deployment_scripts/CleanupOldVersion.sh
    - source_code/Hi/build/libs/hi-1.0-SNAPSHOT.jar