version: 0.1
phases:
  build:
    commands:
      - sed -i -e 's#username_here#$DB_USERNAME#' src/Hi/src/main/resources/application.properties
      - sed -i -e 's#password_here#$DB_PASSWORD#' src/Hi/src/main/resources/application.properties
      - sed -i -e 's#dbUrl_here#jdbc:mysql://$DB_LINK:3306/$DB_Name#' src/Hi/src/main/resources/application.properties
      - gradle build -p src/Hi/
artifacts:
  type: zip
  files:
    - appspec.yml
    - AppStart.sh
    - AppStop.sh
    - src/Hi/build/libs/hi-1.0-SNAPSHOT.jar